### PR TITLE
Change Max Virtual Channels from 30 to 100

### PR DESCRIPTION
**Pull request by kosenko-max**
Based on #414 request propose to let MK2 use more channels and see how it works.

### CODE REVIEW

**Comment by stieg** [comment]
ok to test

**Comment by stieg** [comment]
Looks sane to me.  Doesn't interfere with the `LoggerConfig` struct in any way.  Ideally this would go in 2.9.0 but should be able to work in 2.8.8.  Only thing I would want to do before merging this would be to test it locally.

**Comment by stieg** [comment]
Tested this locally.  While I am able to add 100 channels and have things work locally, I have stumbled onto another bug.  File Writing isn't working and the ChannelSample type isn't getting populated like it should.

@kosenko-max Since this is a new feature (expansion of virtual channel support) lets target this towards 2.9.0 instead of 2.8.8 (which is a bugfix release).  I'll build upon your patch and get this into 2.9.0.  Thanks for the submission.

**Comment by kosenko-max** [comment]
I'm still unable to make build system to setup logging on my car. If you see that 100 channels is a feature and File Writing or ChannelSample bugs are not in effect with 30 channels - yes, it's probably 2.9.0. Although I'm not sure when it will come.

**Comment by stieg** [comment]
> I'm still unable to make build system to setup logging on my car. If you see that 100 channels is a feature and File Writing or ChannelSample bugs are not in effect with 30 channels - yes, it's probably 2.9.0.

**Comment by stieg** [comment]
Dang it.  ok to test.

**Comment by stieg** [comment]
Hey @kosenko-max,
   I hear ya.  I don't know why its breaking off-hand either.  Definitely a regression though with the file writing.  I'll look at patching up the vagrant image so that you can build with it.  Then, if you are so inclined, you can build your own version of the firmware before its released to play with.

**Comment by stieg** [comment]
Solved the bug.  See #444

**Comment by stieg** [comment]
Just tested this with a workaround to the issue... works fine as far as I can tell.

**Comment by stieg** [comment]
Since this will go against 2.9.0, I have re-opened another PR with patches from this PR rebased onto r/2.9.0.  See PR autosportlabs/RaceCapture-Pro_firmware/pull/446.  Going to close this one.

**Pull request closed without merging**
