### PR TITLE
Remove de-init code in USB driver when USB gets suspended

### PR DESCRIPTION
**Pull request by stieg**
This causes the device to never return to an awake state when the
USB subsustem goes into sleep mode.  The simple fix here is to
remove the call since power consumption is not a high priority for
us.  The better fix would be to fix it so that we return from sleep
when we move away from suspend.  Patches welcome.

Fixes issue #426

### CODE REVIEW

**Comment by brentpicasso** [comment]
awesome. :shipit:

**Comment by stieg** [comment]
Well @Jeff-Ciesielski is sending me warning about doom with this because of ISR storms when no USB is connected.  So need further testing and validation before I merge this.

**Comment by stieg** [comment]
The double not clamp is to ensure that its treated as a bool.  Its probably not necessary.  I can get rid of it as needed.

**Comment by Jeff-Ciesielski** [comment]
Lack of a true bool type has always been a bit of an annoyance in C.  On the one hand, I could ask the question "who would do something like decrement/increment/modify something marked bool".  On the other, I've actually seen someone perform math on a bool causing some really subtle bugs :(.

I can see the benefit, but do you think perhaps a "CLAMP_TO_BOOL" macro would make sense for readability?

**Comment by stieg** [comment]
> I've actually seen someone perform math on a bool causing some really subtle bugs :(.

Oh god.

> I can see the benefit, but do you think perhaps a "CLAMP_TO_BOOL" macro would make sense for readability?

Sure.  Can easily do that.

**Comment by brentpicasso** [comment]
Looks sane. I've never reproduced this, so I'll just test the normal operation on my kernel after this gets merged to ensure everything worked as before.

:shipit:

**Pull request merged**
