### PR TITLE
Accept only high quality GPS samples in predictive time code

### PR DESCRIPTION
**Pull request by stieg**
Adds checks that ensure we only accept high quality GPS snapshot values.  "High quality" is defined as:

* Differential GPS is available
* Our dilution of precision <= 2.0

The idea here is that low quality samples are getting into our predictive timer when racers are going under bridges or near mountains that can briefly affect the GPS quality.  By restricting what samples we accept we ensure that the samples we do have are of high enough quality to be "accurate enough".  This will translate into more accurate predictive times and hopefully eliminate the jumps some users are seeing when they get inaccurate samples in the predictive timer queue.

The potential downside to this is that there are longer periods of time where we don't record samples.  This will make the system much less accurate.  However I am willing to accept this risk because of how much the system already relies on high GPS accuracy.

Also there is a patch here that addresses newer GCC compilation issues.

Issue #108

### CODE REVIEW

**Comment by brentpicasso** [comment]
Looks pretty straightforward. I think we should road test this before we merge. I can do it; are you set up to do it also?

**Comment by stieg** [comment]
Wow totally missed the comment.  Not really setup currently but could be.  Probably would just use RCT as that is easier to muck with.

**Comment by brentpicasso** [comment]
No problem; can do a drive test this weekend too.

**Comment by brentpicasso** [comment]
More data; This video from Matt shows the lap time freezing then showing a very high value moments before end of lap. Apparently this was repeatable lap-to-lap.   We need to access the data to verify, but from the terrain it looks like there's no reason GPS would suddenly degrade. 

https://www.youtube.com/watch?v=3Lf4Mojoa6I

**Comment by stieg** [comment]
@brentpicasso Lets solve one issue at a time.  I'm sure there are several.  Unless you see good reason not to merge this lets get it in.

**Comment by brentpicasso** [comment]
agreed. :shipit:

**Pull request merged**
