### PR TITLE
Improve mk2 sdcard situation

### PR DESCRIPTION
**Pull request by stieg**
Adds a patch to our sdcard lib to make it not do things twice and improve its sanity.  Also adds some `taskYIELD` methods to the sdcard driver to prevent it from starving the rest of the system from resources.  Also increases the stack size of the fileWriter task so it doesn't go boom boom all over the other tasks.  Also removes any masking of interrupts and adds some general improvements to our sdcard code.  Finally, adds small debugging and Makefile improvements.

### CODE REVIEW

**Comment by brentpicasso** [comment]
doing a top level make clean; make yields an error:


.build/../../src/command/baseCommands.o: In function `ShowTaskInfo':
/home/brent/git-projects/RaceCapture-Pro_firmware/platform/rct/../../src/command/baseCommands.c:103: undefined reference to `vTaskList'
collect2: error: ld returned 1 exit status
make[3]: *** [.build/main.elf] Error 1
make[3]: Leaving directory `/home/brent/git-projects/RaceCapture-Pro_firmware/platform/rct'
make[2]: *** [rct-build] Error 2
make[2]: Leaving directory `/home/brent/git-projects/RaceCapture-Pro_firmware'
make[1]: *** [rct-pristine] Error 2
make[1]: Leaving directory `/home/brent/git-projects/RaceCapture-Pro_firmware'
make: *** [package] Error 2

**Comment by stieg** [comment]
The 2.9 series isn't supposed to built RCT.  That starts with 2.10.

**Comment by stieg** [comment]
@brentpicasso Fixed

**Comment by brentpicasso** [comment]
tested this directly. :shipit:

**Pull request merged**
