### PR TITLE
GSumMax - preliminary implementation resolves #1058

### LINKED ISSUE #1058: GSum Max for the lap / GSum percentage of max
Enhance the current GSum channel to track Gsum max per segment of the race track, and then track real-time percentage-of-max. 

After the first lap is established, divide the track into N number of segments (e.g. 100), by distance from start/finish. 

During the progress of the lap, and following laps, update the current segment (by distance) with the max gsum value, and keep updating these segments as needed.

Finally, compute a "FlatOut" score which is the percentage-of-max for the current gsum value and record that as the current FlatOut score.   (GSum / GSumMax[segment]) * 100

Channels: 
GSum - existing GSum channel
GSumMax - max Gsum per segment of track
FlatOut - 0-100 percentage of current GSum value against the GSumMax at that segment of the track

### PR DESCRIPTION
**Pull request by RodADavison**
I have done some preliminary testing and appears to work as designed.  I will do more testing after a code review.

### CODE REVIEW

**Comment by RodADavison** [comment]
@brentpicasso do you know what to do about the merge conflicts in the test folder?  I'm confused about those.  If you're OK with it as is, I'll do a bit more testing today and let you take it this evening.

**Comment by brentpicasso** [comment]
Not sure about the conflicts. If this was cleanly branched from r/2.18.0, then it would be impossible to have conflicts. 

e.g.

```
git checkout r/2.18.0
git pull
git checkout -b p/brent/my_new_branch
```

Try this.  Save those conflicted files off to the side, then do a git merge r/2.18.0 - this will pull in all the latest code from r/2.18.0. 

This sequence gets the latest from r/2.18.0, then merges anything in r/2.18.0 not in your branch:

```
git checkout r/2.18.0
git pull
git checkout p/rod/gSumMax
git merge r/2.18.0
```
You may get a conflict, you'll have a chance to resolve it at that time.

**Comment by RodADavison** [comment]
It seems I wasn't quite uptodate!?  I thought I'd started with a clean 2.18.0.  Seems to be resolved now.  Will test today.

**Comment by RodADavison** [comment]
Went out for a test drive this evening ... subsequent data examination looks good.  Ship it whenever you're ready!

**Pull request merged**
