### PR TITLE
Fix up the Vagrant environment

### PR DESCRIPTION
**Pull request by stieg**
Fixes it up and improves on it by doing the following:

* Makes the CPU selection dynamic so you use your computer's resources
* Removes installation of MK1 toolchain since we don't support it in
  this repo anymore
* Fixes the auto-provisioning so that it works again

### CODE REVIEW

**Comment by stieg** [comment]
Addresses #441

**Comment by stieg** [comment]
Since this isn't related to the code (build env) I'm just going to merge.  This is more formality than anything to let others know what is happening.

**Comment by kosenko-max** [comment]
==> default: stdin: is not a tty
==> default: Dropping privileges to vagrant user

**Comment by kosenko-max** [comment]
==> default: Get:108 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libc6-prof amd64 2.19-0ubuntu6.7 [1,520 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory

**Comment by kosenko-max** [comment]
I don't know why those one reds also:
==> default: Wrote /etc/emacs24/site-start.d/00debian-vars.elc
==> default: Wrote /usr/share/emacs24/site-lisp/debian-startup.elc

**Comment by stieg** [comment]
Yeah... I don't know either.  But try building it.  It worked for me when I built it from a clean vagrant environment.  If you do a clean vagrant build and it doesn't work, let me know.

**Comment by kosenko-max** [comment]
Installed fresh. Looks fine. Except that after install vagrant folder on the Guest Ubuntu is empty. It's empty under root as well. Should I mount it somehow? I saw same before - fresh install it has shared content, restart machine and it's empty...

**Comment by kosenko-max** [comment]
Also, for some reasons it has assigned 4 CPU to the machine while I only have 2.

**Comment by stieg** [comment]
> Installed fresh. Looks fine. Except that after install vagrant folder on the Guest Ubuntu is empty. It's empty under root as well. 

You mean `/vagrant` is showing no files?  It should be showing you the contents of the directory containing the `Vagrantfile` (which should be the firmware repo).

> Should I mount it somehow?

Vagrant should be mounting it for you automatically.  Its part of the vagrant process.

> I saw same before - fresh install it has shared content, restart machine and it's empty...

Ahh yes.  Vagrant is finicky.  If the shared directory goes away, try the `vagrant reload` command.

> Also, for some reasons it has assigned 4 CPU to the machine while I only have 2.

You are on a Mac?  Hyperthreading enabled?  That would make 2 physical CPUs show up as 4 logical CPUs.  That was a new feature I added today (Dynamic CPU counting in the Vagrant file).

**Pull request merged**
